# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.11

    # working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      - run: python --version
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      # Step 3: run linter
      - run:
          name: run PEP8 on python file
          command: |
            . venv/bin/activate
            flake8 -v calculator.py --statistics
      # Step 3: run tests
      - run:
          name: run tests addition
          command: |
            . venv/bin/activate
            pytest -v test_addition.py
      
      - run:
          name: run tests subtract
          command: |
            . venv/bin/activate
            pytest -v test_substract.py

      - run:
          name: run tests multiply
          command: |
            . venv/bin/activate
            pytest -v test_multiply.py
      # Step 3: run coverage test
      - run:
          name: run coverage test
          command: |
            . venv/bin/activate
            pytest -v --cov=calculator
      
      - run:
          name: OK
          command: |
            . venv/bin/activate
            echo "everything is good"
